[description]
other = "当需要实时信息（如天气、新闻、股票价格、汇率、最新事件等）时，调用此工具进行网络搜索。根据用户的输入生成搜索关键词列表"

[param_description]
other = "搜索关键词。对于必须完整匹配的精确短语，使用双引号括起来，例如：\"Hello world\"。多个概念之间用空格组合。示例：C++ \"Hello world\" 历史"

[pending]
other = "正在搜索"
