package agent

import (
	"encoding/json"
	"fmt"
	"net/http"

	"BrainForever/infra/httpx/sse"
	"BrainForever/infra/i18n"
	"BrainForever/infra/llm"
	"BrainForever/internal/agent/toolimp"
)

// ============================================================
// ChatHandler — POST /api/chat handler (core)
// ============================================================

// Enqueue a new message for request, assign an ID.
// Writes directly to DB — no in-memory message storage.
// Must be called with session.mu held.
func appendNewRequestMessage(session *session, reqMsg *Message) {
	if reqMsg.ID != 0 {
		panic(fmt.Sprintf("new request message's ID is not 0, but %d", reqMsg.ID))
	}

	var lastID int64 = 0

	// Load the last message from DB to determine the next ID
	var dbSessionID int64
	if session.currentChat.dbChat != nil {
		dbSessionID = session.currentChat.dbChat.ID
	}
	if dbSessionID > 0 {
		dbMessages, err := session.chatStore.ListMessages(dbSessionID)
		if err == nil && len(dbMessages) > 0 {
			lastMsg := dbMessages[len(dbMessages)-1]
			lastID = int64(lastMsg.GroupIndex)
		}
	}

	reqMsg.ID = lastID + 1

	// Ensure a DB session record exists
	ensureDBSession(session)

	// Persist the user message to DB
	persistMessageToDB(session, reqMsg)
}

// resolveNewMessageRequest parses and validates the incoming chat request.
// Returns nil if validation fails (the caller should return immediately in that case).
func (h *ChatAgent) resolveNewMessageRequest(w http.ResponseWriter, r *http.Request) *ChatRequest {
	// Only accept POST
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return nil
	}

	// Parse request
	var req ChatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, fmt.Sprintf("failed to parse request. %v", err), http.StatusBadRequest)
		return nil
	}

	if req.Message.Content == "" {
		http.Error(w, "message content cannot be empty", http.StatusBadRequest)
		return nil
	} else if req.Message.ID != 0 {
		http.Error(w, "new message's id  must be zero", http.StatusBadRequest)
		return nil
	}

	return &req
}

// OnNewMessage handles POST /api/chat requests
func (h *ChatAgent) OnNewMessage(w http.ResponseWriter, r *http.Request) {
	// 1. Resolve request
	req := h.resolveNewMessageRequest(w, r)
	if req == nil {
		return
	}

	// 2. Resolve sessionID from cookie (or generate a new one) and get/create the session
	sessionID := h.resolveSessionID(w, r)
	session := h.sessionManager.GetOrCreate(sessionID)

	session.mu.Lock()

	// 3. Determine the language for this request.
	// Priority: request header Accept-Language > handler defaultLang > "en"
	lang := i18n.GetAcceptLanguage(r.Header.Get("Accept-Language"))
	if lang == "" {
		lang = h.defaultLang
	}

	// 4. Add the message to the messages and assign it a unique ID
	appendNewRequestMessage(session, &req.Message)

	if req.Message.ID <= 0 {
		session.mu.Unlock()
		panic("new message's ID is zero still after append to messages")
	}

	// 5. Load messages from DB for the LLM call
	llmMsgs, err := loadMessagesAsLLMMessages(session)
	session.mu.Unlock()

	if err != nil {
		http.Error(w, fmt.Sprintf("failed to load messages: %v", err), http.StatusInternalServerError)
		return
	}

	startSystemMsg := llm.Message{
		Role:    llm.RoleSystem,
		Content: makeFixSystemPromptContent(lang),
	}
	messages := make([]llm.Message, 0, 1+len(llmMsgs))
	messages = append(messages, startSystemMsg)
	messages = append(messages, llmMsgs...)

	// 6. Create SSE writer
	sseWriter := sse.NewSSEWriter(w)

	// 7. Build tool definitions with translated descriptions.
	// time_query tool is always available.
	// web_search tool is only provided when WebSearchEnabled is true.
	timeQueryToolImp := toolimp.MakeTimeQueryTool(lang)
	toolsImp := []llm.ToolIMP{timeQueryToolImp}

	if req.WebSearchEnabled {
		webSearchToolImp := toolimp.MakeWebSearchTool(r.Context(), h.webSearcher, lang)
		toolsImp = append(toolsImp, webSearchToolImp)
	}

	// 8. If this is a new chat (SN was just generated by ensureDBSession),
	//    send a chat_created event so the frontend can promote blankItem to items[]
	//    and update the sidebar immediately.
	//    Also pass front_sn back so the frontend can map the temporary SN to the real SN.
	session.mu.Lock()
	if session.currentChat.dbChat != nil && session.currentChat.dbChat.SN != "" {
		sseWriter.WriteEvent(SSEEvent{
			Type:    "chat_created",
			SN:      session.currentChat.dbChat.SN,
			FrontSN: req.FrontSN,
		})
	}
	session.mu.Unlock()

	// 9. Stream with tool call handling
	// callLLMWithPipeline handles the streaming LLM call, tool loop, and SSE events.
	// It returns the assistant message that the caller persists to DB.
	// NOTE: session.mu is NOT held during streaming, allowing other handlers
	// (e.g., OnSwitchChat) to proceed concurrently.
	assistantMsg := h.callLLMWithPipeline(r.Context(), sseWriter,
		req.Message.ID,
		messages,
		toolsImp,
		req.DeepThink,
		lang)

	// 10. Persist the assistant message to DB
	if assistantMsg != nil {
		session.mu.Lock()
		persistMessageToDB(session, assistantMsg)
		session.mu.Unlock()
	}
}

// makeFixSystemPromptContent returns the system prompt content string,
// translated according to the given language.
func makeFixSystemPromptContent(lang string) string {
	return i18n.SystemPrompt.TL(lang, "chat")
}
