// Uses a separate user.db SQLite database to store user information.
package store

import (
	"crypto/md5"
	"database/sql"
	"fmt"
	"math/rand"
	"strings"
	"time"

	"github.com/jmoiron/sqlx"
	_ "github.com/mattn/go-sqlite3"
)

// ============================================================
// User struct
// ============================================================

// User represents user information
type User struct {
	ID       int64  `db:"id"`        // Integer, locally unique (auto-increment primary key)
	Nickname string `db:"nickname"`  // Default nickname, max 38 characters
	UUID     string `db:"uuid"`      // Unique user string generated by this program (32 chars)
	Password string `db:"password"`  // Password: MD5 of raw password + uuid as salt
	CreateAt string `db:"create_at"` // Creation time, defaults to current time
	UpdateAt string `db:"update_at"` // Last update time, defaults to current time on creation, auto-updated on modification
}

// ============================================================
// UserStore
// ============================================================

// UserStore manages user storage
type UserStore struct {
	db *sqlx.DB
}

// NewUserStore creates a new UserStore.
// dbPath is the path to user.db (e.g., "./user.db").
func NewUserStore(dbPath string) (*UserStore, error) {
	db, err := sqlx.Open("sqlite3", dbPath+"?_journal_mode=WAL&_busy_timeout=5000")
	if err != nil {
		return nil, fmt.Errorf("failed to open user database. %w", err)
	}

	store := &UserStore{db: db}
	if err := store.initSchema(); err != nil {
		return nil, err
	}
	return store, nil
}

// initSchema initializes the user table schema
func (s *UserStore) initSchema() error {
	schema := `
		CREATE TABLE IF NOT EXISTS users (
			id        INTEGER PRIMARY KEY AUTOINCREMENT,
			nickname  TEXT    NOT NULL CHECK(length(nickname) <= 38),
			uuid      TEXT    NOT NULL UNIQUE CHECK(length(uuid) = 32),
			password  TEXT    NOT NULL,
			create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
		);

		-- Automatically set update_at to current time when a row in users is updated
		CREATE TRIGGER IF NOT EXISTS trg_users_update_at
			BEFORE UPDATE ON users
			FOR EACH ROW
		BEGIN
			UPDATE users SET update_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
		END;
	`
	_, err := s.db.Exec(schema)
	if err != nil {
		return fmt.Errorf("failed to initialize user table. %w", err)
	}
	return nil
}

// ============================================================
// Password utility functions
// ============================================================

// MD5Hash computes the MD5 hash and returns a 32-character lowercase hex string
func MD5Hash(s string) string {
	return fmt.Sprintf("%x", md5.Sum([]byte(s)))
}

// EncryptPassword encrypts the raw password using uuid as salt with MD5.
// Rule: MD5(rawPassword + uuid)
func EncryptPassword(rawPassword, uuid string) string {
	return MD5Hash(rawPassword + uuid)
}

// ============================================================
// UUID generation utilities
// ============================================================

// generateUUID generates a 32-character unique user string.
// Rule: systemPrefix(5 chars) + YYYYMMDDHHNNSS(14 chars) + milliseconds(3 chars) + random int(5 chars) + luckChars(5 chars)
func generateUUID(systemPrefix, luckChars string) string {
	now := time.Now()
	// Time part: YYYYMMDDHHNNSS + 3-digit milliseconds
	timePart := now.Format("20060102150405") + fmt.Sprintf("%03d", now.Nanosecond()/1e6)
	// 5-digit random integer (zero-padded to 5 digits)
	randPart := fmt.Sprintf("%05d", rand.Intn(100000))
	return systemPrefix + timePart + randPart + luckChars
}

// ============================================================
// User operations
// ============================================================

// CreateUser creates a new user.
// nickname is the default nickname (max 38 chars), rawPassword is the raw password.
// systemPrefix is the system fixed prefix (5 chars), luckChars is the custom suffix (5 chars).
// uuid is auto-generated internally, password is automatically computed as MD5(rawPassword + uuid).
// When creating a user, the first default role (role_no=0, role_name="self") is also created automatically.
func (s *UserStore) CreateUser(systemPrefix, luckChars, nickname, rawPassword string) (*User, error) {
	// Validate nickname length
	if len(nickname) > 38 {
		return nil, fmt.Errorf("nickname too long. max 38 characters, got %d", len(nickname))
	}
	if len(nickname) == 0 {
		return nil, fmt.Errorf("nickname cannot be empty")
	}

	// Validate password
	if len(rawPassword) == 0 {
		return nil, fmt.Errorf("password cannot be empty")
	}

	// Validate systemPrefix
	if len(systemPrefix) != 5 {
		return nil, fmt.Errorf("systemPrefix must be 5 characters. got %d", len(systemPrefix))
	}

	// Validate luckChars
	if len(luckChars) != 5 {
		return nil, fmt.Errorf("luckChars must be 5 characters. got %d", len(luckChars))
	}

	uuid := generateUUID(systemPrefix, luckChars)
	password := EncryptPassword(rawPassword, uuid)

	tx, err := s.db.Begin()
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction. %w", err)
	}
	defer tx.Rollback()

	// Insert user
	result, err := tx.Exec(
		"INSERT INTO users(nickname, uuid, password) VALUES(?, ?, ?)",
		nickname, uuid, password,
	)
	if err != nil {
		// Check for uuid duplicate
		if strings.Contains(err.Error(), "UNIQUE constraint failed") {
			return nil, fmt.Errorf("duplicate uuid. %w", err)
		}
		return nil, fmt.Errorf("failed to create user. %w", err)
	}

	id, _ := result.LastInsertId()

	// Create the user's first default role
	_, err = tx.Exec(
		"INSERT INTO roles(role_no, role_name, uuid, is_public, is_active) VALUES(?, ?, ?, ?, ?)",
		0, "self", uuid, 0, 1,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create default role. %w", err)
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("failed to commit transaction. %w", err)
	}

	return s.GetUserByID(id)
}

// GetUserByID retrieves a user by ID
func (s *UserStore) GetUserByID(id int64) (*User, error) {
	var u User
	err := s.db.Get(&u, "SELECT id, nickname, uuid, password, create_at, update_at FROM users WHERE id = ?", id)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found (id=%d)", id)
		}
		return nil, fmt.Errorf("failed to query user. %w", err)
	}
	return &u, nil
}

// GetUserByUUID retrieves a user by uuid
func (s *UserStore) GetUserByUUID(uuid string) (*User, error) {
	var u User
	err := s.db.Get(&u, "SELECT id, nickname, uuid, password, create_at, update_at FROM users WHERE uuid = ?", uuid)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found (uuid=%s)", uuid)
		}
		return nil, fmt.Errorf("failed to query user. %w", err)
	}
	return &u, nil
}

// VerifyPassword verifies if the user's password is correct.
// rawPassword is the raw password to verify; it computes MD5 with the user's uuid as salt and compares.
func (s *UserStore) VerifyPassword(uuid, rawPassword string) (bool, error) {
	u, err := s.GetUserByUUID(uuid)
	if err != nil {
		return false, err
	}
	return u.Password == EncryptPassword(rawPassword, u.UUID), nil
}

// UpdateNickname updates the user's nickname
func (s *UserStore) UpdateNickname(id int64, newNickname string) error {
	if len(newNickname) > 38 {
		return fmt.Errorf("nickname too long. max 38 characters, got %d", len(newNickname))
	}
	if len(newNickname) == 0 {
		return fmt.Errorf("nickname cannot be empty")
	}

	result, err := s.db.Exec("UPDATE users SET nickname = ? WHERE id = ?", newNickname, id)
	if err != nil {
		return fmt.Errorf("failed to update nickname. %w", err)
	}
	rows, _ := result.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("user not found (id=%d)", id)
	}
	return nil
}

// UpdatePassword updates the user's password.
// Automatically re-computes MD5 using the existing uuid as salt.
func (s *UserStore) UpdatePassword(id int64, newRawPassword string) error {
	if len(newRawPassword) == 0 {
		return fmt.Errorf("password cannot be empty")
	}

	// First get user info to obtain uuid
	u, err := s.GetUserByID(id)
	if err != nil {
		return err
	}

	newPassword := EncryptPassword(newRawPassword, u.UUID)
	_, err = s.db.Exec("UPDATE users SET password = ? WHERE id = ?", newPassword, id)
	if err != nil {
		return fmt.Errorf("failed to update password. %w", err)
	}
	return nil
}

// DeleteUser deletes a user and all their roles.
// Before deleting the user, all their roles are deleted first.
func (s *UserStore) DeleteUser(id int64) error {
	// First get user info to obtain uuid
	u, err := s.GetUserByID(id)
	if err != nil {
		return err
	}

	tx, err := s.db.Begin()
	if err != nil {
		return fmt.Errorf("failed to begin transaction. %w", err)
	}
	defer tx.Rollback()

	// First delete all roles for this user
	_, err = tx.Exec("DELETE FROM roles WHERE uuid = ?", u.UUID)
	if err != nil {
		return fmt.Errorf("failed to delete user roles. %w", err)
	}

	// Then delete the user
	result, err := tx.Exec("DELETE FROM users WHERE id = ?", id)
	if err != nil {
		return fmt.Errorf("failed to delete user. %w", err)
	}
	rows, _ := result.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("user not found (id=%d)", id)
	}

	return tx.Commit()
}

// ListUsers lists all users
func (s *UserStore) ListUsers() ([]User, error) {
	var users []User
	err := s.db.Select(&users, "SELECT id, nickname, uuid, password, create_at, update_at FROM users ORDER BY id")
	if err != nil {
		return nil, fmt.Errorf("failed to list users. %w", err)
	}
	return users, nil
}

// Close closes the database connection
func (s *UserStore) Close() error {
	return s.db.Close()
}
