// Uses the global MySQL connection (theMySQLDBC) to store user information.
package store

import (
	"crypto/md5"
	"crypto/rand"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"BrainForever/infra/i18n"
	"BrainForever/internal/store/dbpath"
	"BrainForever/toolset"
)

// ============================================================
// User struct
// ============================================================

// User represents user information
type User struct {
	ID          int64  `db:"id"`           // Integer, locally unique (auto-increment primary key)
	No          string `db:"no"`           // Fixed 6-character user number (ASCII)
	SN          string `db:"sn"`           // Unique user serial number generated by this program (ASCII)
	Tel         string `db:"tel"`          // Phone number, max 18 chars, NOT NULL default '' (empty = unverified)
	Nickname    string `db:"nickname"`     // Default nickname, max 38 UTF-8 characters (rune count, not byte count)
	Password    string `db:"password"`     // Password: MD5 of raw password + salt
	Salt        string `db:"salt"`         // Salt for password encryption (random hex string)
	Deleted     int    `db:"deleted"`      // Soft delete flag, 0 = active, 1 = deleted
	SettingsVer int    `db:"settings_ver"` // User settings version, default 0
	Settings    string `db:"settings"`     // User settings JSON
	CreateAt    string `db:"create_at"`    // Creation time, defaults to current time
	UpdateAt    string `db:"update_at"`    // Last update time, defaults to current time on creation, auto-updated on modification
}

// ============================================================
// UserStore
//
// UserStore does NOT hold its own *sqlx.DB connection.
// It uses the global MySQL connection via TheMySQLDB().
// This allows multiple stores (UserStore, future PaymentStore, etc.)
// to share the same MySQL connection pool.
// ============================================================

// UserStore manages user storage
type UserStore struct {
	// No db field — uses the global TheMySQLDB() singleton.
}

// OpenUserStore creates a UserStore backed by the global MySQL connection.
// The MySQL tables (users, etc.) are assumed to already exist —
// they must be created manually or via migration script before starting the server.
// The actual MySQL connection is managed globally via InitMySQLDB / TheMySQLDB().
func OpenUserStore() (*UserStore, error) {
	return &UserStore{}, nil
}

// NewUserStore creates a new UserStore.
// Deprecated: Use OpenUserStore instead.
func NewUserStore() (*UserStore, error) {
	return OpenUserStore()
}

// ============================================================
// Global singleton
// ============================================================

var (
	theUserStore *UserStore
	theDBDir     string // database directory, used by Login/Logout
)

// TheUserStore returns the global UserStore singleton.
// Panics if InitTheUserStore has not been called.
func TheUserStore() *UserStore {
	if theUserStore == nil {
		panic("TheUserStore is nil - call InitTheUserStore first")
	}
	return theUserStore
}

// InitTheUserStore creates the global UserStore singleton and ensures its schema.
// dbDir is the directory for per-user SQLite database files, e.g. "localdb".
// The MySQL connection must already be initialized via InitMySQLDB() before calling this.
// Opens before HTTP server starts listening.
func InitTheUserStore(dbDir string) error {
	s, err := OpenUserStore()
	if err != nil {
		return err
	}
	theDBDir = dbDir
	theUserStore = s
	return nil
}

// CloseTheUserStore closes the global UserStore.
// Called after HTTP server stops listening (via defer in main).
func CloseTheUserStore() {
	if theUserStore != nil {
		theUserStore.Close()
	}
}

// ============================================================
// Password utility functions
// ============================================================

// md5Hash computes the MD5 hash and returns a 32-character lowercase hex string
func md5Hash(s string) string {
	return fmt.Sprintf("%x", md5.Sum([]byte(s)))
}

// encryptPassword encrypts the raw password using salt with MD5.
// Rule: MD5(rawPassword + salt)
func encryptPassword(rawPassword, salt string) string {
	return md5Hash(rawPassword + salt)
}

// ============================================================
// Salt generation utilities
// ============================================================

// generateSalt generates a random 32-character hex string for use as a password salt.
func generateSalt() string {
	b := make([]byte, 16) // 16 bytes -> 32 hex chars
	if _, err := rand.Read(b); err != nil {
		// Fallback: should never happen on modern OS
		return fmt.Sprintf("%x", md5.Sum([]byte(fmt.Sprintf("%d", time.Now().UnixNano()))))
	}
	return fmt.Sprintf("%x", b)
}

// generateUserNO generates a unique 6-character user number.
// Format: 1 uppercase letter (excluding I, O, Z) + 5 random digits.
// Checks DB for duplicates and retries up to 5 times.
// Returns empty string if all attempts fail due to collisions.
func (s *UserStore) generateUserNO() string {
	const letters = "ABCDEFGHJKLMNPQRSTUVWXY" // A-Z excluding I, O, Z (23 letters)

	for attempt := 0; attempt < 5; attempt++ {
		// Pick a random letter
		lb := make([]byte, 1)
		rand.Read(lb)
		letter := letters[int(lb[0])%len(letters)]

		// Generate 5 random digits
		db := make([]byte, 5)
		rand.Read(db)
		digits := fmt.Sprintf("%05d",
			int(db[0])%10*10000+
				int(db[1])%10*1000+
				int(db[2])%10*100+
				int(db[3])%10*10+
				int(db[4])%10)

		candidate := string(letter) + digits

		// Check if already exists (uses unique index, no full scan)
		var exists int
		err := TheMySQLDB().Get(&exists, "SELECT EXISTS(SELECT 1 FROM users WHERE no = ?)", candidate)
		if err != nil {
			continue // DB error, try again
		}
		if exists == 0 {
			return candidate
		}
	}
	return "" // All 5 attempts failed due to collisions
}

// ============================================================
// User operations
// ============================================================

// FindOrCreateByTel looks up a user by phone number (excluding deleted users).
// If found, returns the existing user.
// If not found, creates a new user with the given tel as nickname prefix and a default password.
// FindOrCreateByTel returns an existing user by tel, or creates a new one if not found.
// isNew is true when a new user was created.
func (s *UserStore) FindOrCreateByTel(tel string) (user *User, isNew bool, err error) {
	// Try to find existing user by tel (exclude deleted)
	existing, lookupErr := s.GetUserByTel(tel, false)
	if lookupErr != nil {
		err = lookupErr
		return
	}
	if existing != nil {
		user = existing // already registered
		return
	}

	// Auto-register new user
	// Use tel suffix as nickname (last 4 digits for privacy)
	nickname := tel
	if len(tel) >= 4 {
		nickname = "U" + tel[len(tel)-4:]
	}

	createdUser, createErr := s.CreateUser(nickname, tel) // use tel as the default password
	if createErr != nil {
		err = fmt.Errorf("failed to auto-register user: %w", createErr)
		return
	}

	// Update the tel field after creation
	_, execErr := TheMySQLDB().Exec("UPDATE users SET tel = ? WHERE id = ?", tel, createdUser.ID)
	if execErr != nil {
		err = fmt.Errorf("failed to set tel for new user: %w", execErr)
		return
	}

	// Re-fetch to get updated user
	user, lookupErr = s.GetUserByID(createdUser.ID, false)
	if lookupErr != nil {
		err = lookupErr
		return
	}

	isNew = true
	return
}

// CreateUser creates a new user.
// nickname is the default nickname (max 38 chars), rawPassword is the raw password.
// sn is auto-generated via toolset.GenerateSN("u-"), salt is auto-generated randomly,
// password is automatically computed as MD5(rawPassword + salt).
func (s *UserStore) CreateUser(nickname, rawPassword string) (*User, error) {
	sn := toolset.GenerateSN("u-")
	no := s.generateUserNO()
	if no == "" {
		return nil, fmt.Errorf("failed to generate unique user number")
	}
	salt := generateSalt()
	password := encryptPassword(rawPassword, salt)

	result, err := TheMySQLDB().Exec(
		"INSERT INTO users(nickname, no, sn, salt, password, tel, settings_ver, settings) VALUES(?, ?, ?, ?, ?, ?, 0, ?)",
		nickname, no, sn, salt, password, "", "{}",
	)
	if err != nil {
		// Check for sn duplicate
		if strings.Contains(err.Error(), "Duplicate entry") {
			return nil, fmt.Errorf("duplicate sn: %w", err)
		}
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	id, _ := result.LastInsertId()
	return s.GetUserByID(id, false)
}

// GetUserByID retrieves a user by ID.
// If includeDeleted is false, only active (deleted=0) users are returned.
func (s *UserStore) GetUserByID(id int64, includeDeleted bool) (*User, error) {
	var u User
	query := "SELECT id, nickname, no, sn, salt, password, tel, deleted, settings_ver, settings, create_at, update_at FROM users WHERE id = ?"
	if !includeDeleted {
		query += " AND deleted = 0"
	}
	err := TheMySQLDB().Get(&u, query, id)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found (id=%d)", id)
		}
		return nil, fmt.Errorf("failed to query user: %w", err)
	}
	return &u, nil
}

// GetUserByNO retrieves a user by no (user number).
// If includeDeleted is false, only active (deleted=0) users are returned.
func (s *UserStore) GetUserByNO(no string, includeDeleted bool) (*User, error) {
	var u User
	query := "SELECT id, nickname, no, sn, salt, password, tel, deleted, settings_ver, settings, create_at, update_at FROM users WHERE no = ?"
	if !includeDeleted {
		query += " AND deleted = 0"
	}
	err := TheMySQLDB().Get(&u, query, no)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found by no=%s", no)
		}
		return nil, fmt.Errorf("failed to query user: %w", err)
	}
	return &u, nil
}

// GetUserByTel retrieves a user by phone number (tel field).
// If includeDeleted is false, only active (deleted=0) users are returned.
// Returns nil if the tel is empty or not found.
func (s *UserStore) GetUserByTel(tel string, includeDeleted bool) (*User, error) {
	if tel == "" {
		return nil, fmt.Errorf("tel is empty")
	}
	var u User
	query := "SELECT id, nickname, no, sn, salt, password, tel, deleted, settings_ver, settings, create_at, update_at FROM users WHERE tel = ?"
	if !includeDeleted {
		query += " AND deleted = 0"
	}
	err := TheMySQLDB().Get(&u, query, tel)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil // not found, not an error
		}
		return nil, fmt.Errorf("failed to query user by tel: %w", err)
	}
	return &u, nil
}

// GetUserBySN retrieves a user by sn.
// If includeDeleted is false, only active (deleted=0) users are returned.
func (s *UserStore) GetUserBySN(sn string, includeDeleted bool) (*User, error) {
	var u User
	query := "SELECT id, nickname, no, sn, salt, password, tel, deleted, settings_ver, settings, create_at, update_at FROM users WHERE sn = ?"
	if !includeDeleted {
		query += " AND deleted = 0"
	}
	err := TheMySQLDB().Get(&u, query, sn)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found by sn=%s", sn)
		}
		return nil, fmt.Errorf("failed to query user: %w", err)
	}
	return &u, nil
}

// VerifyPassword verifies if the user's password is correct.
// rawPassword is the raw password to verify; it computes MD5 with the user's salt and compares.
func (s *UserStore) VerifyPassword(sn, rawPassword string) (bool, error) {
	u, err := s.GetUserBySN(sn, false)
	if err != nil {
		return false, err
	}
	return u.Password == encryptPassword(rawPassword, u.Salt), nil
}

// UpdateNickname updates the user's nickname
func (s *UserStore) UpdateNickname(id int64, newNickname string) error {
	result, err := TheMySQLDB().Exec("UPDATE users SET nickname = ? WHERE id = ?", newNickname, id)
	if err != nil {
		return fmt.Errorf("failed to update nickname: %w", err)
	}
	rows, _ := result.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("user not found (id=%d)", id)
	}
	return nil
}

// UpdatePassword updates the user's password.
// Automatically re-computes MD5 using the existing salt.
func (s *UserStore) UpdatePassword(id int64, newRawPassword string) error {
	if len(newRawPassword) == 0 {
		return fmt.Errorf("password cannot be empty")
	}

	// First get user info to obtain salt
	u, err := s.GetUserByID(id, false)
	if err != nil {
		return err
	}

	newPassword := encryptPassword(newRawPassword, u.Salt)
	_, err = TheMySQLDB().Exec("UPDATE users SET password = ? WHERE id = ?", newPassword, id)
	if err != nil {
		return fmt.Errorf("failed to update password: %w", err)
	}
	return nil
}

// DeleteUser deletes a user.
func (s *UserStore) DeleteUser(id int64) error {
	result, err := TheMySQLDB().Exec("DELETE FROM users WHERE id = ?", id)
	if err != nil {
		return fmt.Errorf("failed to delete user: %w", err)
	}
	rows, _ := result.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("user not found (id=%d)", id)
	}
	return nil
}

// ListUsers lists all users
func (s *UserStore) ListUsers() ([]User, error) {
	var users []User
	err := TheMySQLDB().Select(&users, "SELECT id, nickname, no, sn, salt, password, tel, settings_ver, settings, create_at, update_at FROM users ORDER BY id")
	if err != nil {
		return nil, fmt.Errorf("failed to list users: %w", err)
	}
	return users, nil
}

// ============================================================
// Login / Logout
// ============================================================

// loadChats opens a user's chat database and loads the chat list.
func (s *UserStore) loadChats(userID int64, userSN string) ([]Chat, error) {
	p := dbpath.ForUser(theDBDir, userID, userSN, "chats")
	chatStore, err := CreateLocalChat(p)
	if err != nil {
		return nil, fmt.Errorf("failed to open chats for %s: %w", userSN, err)
	}
	defer chatStore.Close()
	return chatStore.ListChats(100)
}

// LoginByPassword authenticates a user by no and password.
// Returns the authenticated user. Caller should load chats separately.
func (s *UserStore) LoginByPassword(no, password string) (*User, error) {
	// Look up user by no (exclude deleted)
	u, err := s.GetUserByNO(no, false)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", i18n.T("api_error_login_failed"), err)
	}

	// Verify password
	if u.Password != encryptPassword(password, u.Salt) {
		return nil, fmt.Errorf("%s: %w", i18n.T("api_error_login_failed"), fmt.Errorf("incorrect password"))
	}

	return u, nil
}

// LoadChats loads a logged-in user's chat list by their SN (no authentication).
// Used to reload chat data for an already authenticated session.
func (s *UserStore) LoadChats(userID int64, userSN string) ([]Chat, error) {
	return s.loadChats(userID, userSN)
}

// Logout is called when a user logs out. Currently a placeholder.
func (s *UserStore) Logout(userSN string) {
	_ = userSN // Future: update last_logout timestamp, etc.
}

// Close is a no-op because UserStore does not own the MySQL connection.
// The global MySQL connection is closed via CloseMySQLDB().
func (s *UserStore) Close() error {
	return nil
}
