// Uses the global PostgreSQL connection (thePGDBC) to store user information.
package store

import (
	"crypto/md5"
	"crypto/rand"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"BrainForever/infra/i18n"
	"BrainForever/infra/zylog"
	"BrainForever/toolset"
)

// ============================================================
// User struct
// ============================================================

// User represents user information
type User struct {
	ID          int64  `db:"id"`           // Integer, locally unique (auto-increment primary key)
	No          string `db:"no"`           // Fixed 6-character user number (ASCII)
	SN          string `db:"sn"`           // Unique user serial number generated by this program (ASCII)
	Tel         string `db:"tel"`          // Phone number, max 18 chars, NOT NULL default '' (empty = unverified)
	Nickname    string `db:"nickname"`     // Default nickname, max 38 UTF-8 characters (rune count, not byte count)
	Password    string `db:"password"`     // Password: MD5 of raw password + salt
	Salt        string `db:"salt"`         // Salt for password encryption (random hex string)
	Deleted     int    `db:"deleted"`      // Soft delete flag, 0 = active, 1 = deleted
	SettingsVer int    `db:"settings_ver"` // User settings version, default 0
	Settings    string `db:"settings"`     // User settings JSON
	CreateAt    string `db:"create_at"`    // Creation time, defaults to current time
	UpdateAt    string `db:"update_at"`    // Last update time, defaults to current time on creation, auto-updated on modification
}

// ============================================================
// UserStore
//
// UserStore does NOT hold its own *sqlx.DB connection.
// It uses the global PostgreSQL connection via ThePGDB().
// ============================================================

// UserStore manages user storage
type UserStore struct {
	logger zylog.Logger
}

// OpenUserStore creates a UserStore backed by the global PostgreSQL connection.
func OpenUserStore(logger zylog.Logger) (*UserStore, error) {
	return &UserStore{
		logger: zylog.WrapWithSubject(logger, "store-user"),
	}, nil
}

// NewUserStore creates a new UserStore.
// Deprecated: Use OpenUserStore instead.
func NewUserStore(logger zylog.Logger) (*UserStore, error) {
	return OpenUserStore(logger)
}

// ============================================================
// Global singleton
// ============================================================

var (
	theUserStore *UserStore
	theDBDir     string // database directory, kept for backward compatibility
)

// TheUserStore returns the global UserStore singleton.
func TheUserStore() *UserStore {
	if theUserStore == nil {
		panic("TheUserStore is nil - call InitTheUserStore first")
	}
	return theUserStore
}

// InitTheUserStore creates the global UserStore singleton.
func InitTheUserStore(dbDir string, logger zylog.Logger) error {
	s, err := OpenUserStore(logger)
	if err != nil {
		return err
	}
	theDBDir = dbDir
	theUserStore = s
	return nil
}

// CloseTheUserStore closes the global UserStore.
func CloseTheUserStore() {
	if theUserStore != nil {
		theUserStore.Close()
	}
}

// ============================================================
// Password utility functions
// ============================================================

func md5Hash(s string) string {
	return fmt.Sprintf("%x", md5.Sum([]byte(s)))
}

func encryptPassword(rawPassword, salt string) string {
	return md5Hash(rawPassword + salt)
}

func generateSalt() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("%x", md5.Sum([]byte(fmt.Sprintf("%d", time.Now().UnixNano()))))
	}
	return fmt.Sprintf("%x", b)
}

func (s *UserStore) generateUserNO() string {
	const letters = "ABCDEFGHJKLMNPQRSTUVWXY"

	for attempt := 0; attempt < 5; attempt++ {
		lb := make([]byte, 1)
		rand.Read(lb)
		letter := letters[int(lb[0])%len(letters)]

		db := make([]byte, 5)
		rand.Read(db)
		digits := fmt.Sprintf("%05d",
			int(db[0])%10*10000+
				int(db[1])%10*1000+
				int(db[2])%10*100+
				int(db[3])%10*10+
				int(db[4])%10)

		candidate := string(letter) + digits

		var exists bool
		err := ThePGDB().Get(&exists, "SELECT EXISTS(SELECT 1 FROM users WHERE no = $1)", candidate)
		if err != nil {
			continue
		}
		if !exists {
			return candidate
		}
	}
	return ""
}

// ============================================================
// User operations
// ============================================================

// FindOrCreateByTel looks up a user by phone number.
func (s *UserStore) FindOrCreateByTel(tel string) (user *User, isNew bool, err error) {
	existing, lookupErr := s.GetUserByTel(tel, false)
	if lookupErr != nil {
		err = lookupErr
		return
	}
	if existing != nil {
		user = existing
		return
	}

	nickname := tel
	if len(tel) >= 4 {
		nickname = "U" + tel[len(tel)-4:]
	}

	createdUser, createErr := s.CreateUser(nickname, tel)
	if createErr != nil {
		err = fmt.Errorf("failed to auto-register user: %w", createErr)
		return
	}

	sqlUpdateTel := "UPDATE users SET tel = $1 WHERE id = $2"
	_, execErr := ThePGDB().Exec(sqlUpdateTel, tel, createdUser.ID)
	if execErr != nil {
		s.logger.Errorf("SQL [%s] args=[tel=%s id=%d]: %v", sqlUpdateTel, tel, createdUser.ID, execErr)
		err = fmt.Errorf("failed to set tel for new user: %w", execErr)
		return
	}

	user, lookupErr = s.GetUserByID(createdUser.ID, false)
	if lookupErr != nil {
		err = lookupErr
		return
	}

	isNew = true
	return
}

// CreateUser creates a new user.
func (s *UserStore) CreateUser(nickname, rawPassword string) (*User, error) {
	sn := toolset.GenerateSN("u-")
	no := s.generateUserNO()
	if no == "" {
		return nil, fmt.Errorf("failed to generate unique user number")
	}
	salt := generateSalt()
	password := encryptPassword(rawPassword, salt)

	sqlStr := `INSERT INTO users(nickname, no, sn, salt, password, tel, settings_ver, settings)
		 VALUES($1, $2, $3, $4, $5, $6, 0, $7)
		 RETURNING id, nickname, no, sn, salt, password, tel, deleted, settings_ver, settings, create_at, update_at`
	var user User
	err := ThePGDB().Get(&user, sqlStr, nickname, no, sn, salt, password, "", "{}")
	if err != nil {
		if strings.Contains(err.Error(), "duplicate key") {
			return nil, fmt.Errorf("duplicate sn: %w", err)
		}
		s.logger.Errorf("SQL [%s] args=[nickname=%s no=%s sn=%s]: %v", sqlStr, nickname, no, sn, err)
		return nil, fmt.Errorf("failed to create user: %w", err)
	}
	return &user, nil
}

// GetUserByID retrieves a user by ID.
func (s *UserStore) GetUserByID(id int64, includeDeleted bool) (*User, error) {
	var u User
	query := "SELECT id, nickname, no, sn, salt, password, tel, deleted, settings_ver, settings, create_at, update_at FROM users WHERE id = $1"
	if !includeDeleted {
		query += " AND deleted = FALSE"
	}
	err := ThePGDB().Get(&u, query, id)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found (id=%d)", id)
		}
		s.logger.Errorf("SQL [%s] args=[id=%d]: %v", query, id, err)
		return nil, fmt.Errorf("failed to query user: %w", err)
	}
	return &u, nil
}

// GetUserByNO retrieves a user by no.
func (s *UserStore) GetUserByNO(no string, includeDeleted bool) (*User, error) {
	var u User
	query := "SELECT id, nickname, no, sn, salt, password, tel, deleted, settings_ver, settings, create_at, update_at FROM users WHERE no = $1"
	if !includeDeleted {
		query += " AND deleted = FALSE"
	}
	err := ThePGDB().Get(&u, query, no)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found by no=%s", no)
		}
		s.logger.Errorf("SQL [%s] args=[no=%s]: %v", query, no, err)
		return nil, fmt.Errorf("failed to query user: %w", err)
	}
	return &u, nil
}

// GetUserByTel retrieves a user by phone number.
func (s *UserStore) GetUserByTel(tel string, includeDeleted bool) (*User, error) {
	if tel == "" {
		return nil, fmt.Errorf("tel is empty")
	}
	var u User
	query := "SELECT id, nickname, no, sn, salt, password, tel, deleted, settings_ver, settings, create_at, update_at FROM users WHERE tel = $1"
	if !includeDeleted {
		query += " AND deleted = FALSE"
	}
	err := ThePGDB().Get(&u, query, tel)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		s.logger.Errorf("SQL [%s] args=[tel=%s]: %v", query, tel, err)
		return nil, fmt.Errorf("failed to query user by tel: %w", err)
	}
	return &u, nil
}

// GetUserBySN retrieves a user by sn.
func (s *UserStore) GetUserBySN(sn string, includeDeleted bool) (*User, error) {
	var u User
	query := "SELECT id, nickname, no, sn, salt, password, tel, deleted, settings_ver, settings, create_at, update_at FROM users WHERE sn = $1"
	if !includeDeleted {
		query += " AND deleted = FALSE"
	}
	err := ThePGDB().Get(&u, query, sn)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found by sn=%s", sn)
		}
		s.logger.Errorf("SQL [%s] args=[sn=%s]: %v", query, sn, err)
		return nil, fmt.Errorf("failed to query user: %w", err)
	}
	return &u, nil
}

// VerifyPassword verifies if the user's password is correct.
func (s *UserStore) VerifyPassword(sn, rawPassword string) (bool, error) {
	u, err := s.GetUserBySN(sn, false)
	if err != nil {
		return false, err
	}
	return u.Password == encryptPassword(rawPassword, u.Salt), nil
}

// UpdateNickname updates the user's nickname
func (s *UserStore) UpdateNickname(id int64, newNickname string) error {
	sqlStr := "UPDATE users SET nickname = $1 WHERE id = $2"
	result, err := ThePGDB().Exec(sqlStr, newNickname, id)
	if err != nil {
		s.logger.Errorf("SQL [%s] args=[nickname=%s id=%d]: %v", sqlStr, newNickname, id, err)
		return fmt.Errorf("failed to update nickname: %w", err)
	}
	rows, _ := result.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("user not found (id=%d)", id)
	}
	return nil
}

// UpdatePassword updates the user's password.
func (s *UserStore) UpdatePassword(id int64, newRawPassword string) error {
	if len(newRawPassword) == 0 {
		return fmt.Errorf("password cannot be empty")
	}

	u, err := s.GetUserByID(id, false)
	if err != nil {
		return err
	}

	newPassword := encryptPassword(newRawPassword, u.Salt)
	sqlStr := "UPDATE users SET password = $1 WHERE id = $2"
	_, err = ThePGDB().Exec(sqlStr, newPassword, id)
	if err != nil {
		s.logger.Errorf("SQL [%s] args=[id=%d]: %v", sqlStr, id, err)
		return fmt.Errorf("failed to update password: %w", err)
	}
	return nil
}

// DeleteUser deletes a user.
func (s *UserStore) DeleteUser(id int64) error {
	sqlStr := "DELETE FROM users WHERE id = $1"
	result, err := ThePGDB().Exec(sqlStr, id)
	if err != nil {
		s.logger.Errorf("SQL [%s] args=[id=%d]: %v", sqlStr, id, err)
		return fmt.Errorf("failed to delete user: %w", err)
	}
	rows, _ := result.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("user not found (id=%d)", id)
	}
	return nil
}

// ListUsers lists all users
func (s *UserStore) ListUsers() ([]User, error) {
	var users []User
	sqlStr := "SELECT id, nickname, no, sn, salt, password, tel, settings_ver, settings, create_at, update_at FROM users ORDER BY id"
	err := ThePGDB().Select(&users, sqlStr)
	if err != nil {
		s.logger.Errorf("SQL [%s]: %v", sqlStr, err)
		return nil, fmt.Errorf("failed to list users: %w", err)
	}
	return users, nil
}

// ============================================================
// Login / Logout
// ============================================================

// loadChats loads a user's chat list from the unified PostgreSQL database.
func (s *UserStore) loadChats(userID int64) ([]Chat, error) {
	chatStore := NewChatStore(s.logger)
	chats, err := chatStore.ListAllChats(userID)
	if err != nil {
		s.logger.Errorf("loadChats: ChatStore.ListAllChats(userID=%d) failed: %v", userID, err)
		return nil, fmt.Errorf("failed to load chats for user %d: %w", userID, err)
	}
	return chats, nil
}

// LoginByPassword authenticates a user by no and password.
func (s *UserStore) LoginByPassword(no, password string) (*User, error) {
	u, err := s.GetUserByNO(no, false)
	if err != nil {
		s.logger.Errorf("LoginByPassword: GetUserByNO(no=%s) failed: %v", no, err)
		return nil, fmt.Errorf("%s: %w", i18n.T("api_error_login_failed"), err)
	}

	if u.Password != encryptPassword(password, u.Salt) {
		return nil, fmt.Errorf("%s: %w", i18n.T("api_error_login_failed"), fmt.Errorf("incorrect password"))
	}

	return u, nil
}

// LoadChats loads a logged-in user's chat list.
func (s *UserStore) LoadChats(userID int64) ([]Chat, error) {
	return s.loadChats(userID)
}

// Logout is called when a user logs out.
func (s *UserStore) Logout(userSN string) {
	_ = userSN
}

// Close is a no-op because UserStore does not own the PG connection.
func (s *UserStore) Close() error {
	return nil
}
