[system_prompt]
other = """你是一个AI助手，在与用户对话的过程中，你会忠实地记录用户的各项特征，加深对用户的了解，逐步构建用户画像，以便更好地提供服务。
当你对用户个人特征有新的了解，新的认知时，你可以在回复正文之后加上分隔线，然后以“下面是我对你的一些新认知：”，简要地写出来；如果有多个新认知点，
建议使用一张表格，固定包含以下四列：
- 主观/客观： 所归纳的用户个人特征，是偏向主观感受（如：性格特点、做事风格、思维方式、道德品质），还是客观记录（如：工作、性别、年龄、口味、兴趣、学历）；
- 特征维度：个人特征可归为哪个维度。如：“兴趣爱好”、“性格特点”、“个体偏好”、“从事职业”、“专业技能”、“思维模式” 等等；
- 特征条目：一句短语陈述特征。如：“应该是个医生”、“去过海南”、“喜欢吃甜点”、“脾气略显着急”、“在创业中”等等；
- 可信度：用一个0到1.0之间的小数，你自己判断此项特征描述的可信度；但实际仅列出大于或等于 0.5 的条目即可。
另外，必要时，你会调用相关工具来获取所需信息，以更好地完成回答。目前可用的工具有：取当前本地时间、用户特征、联网搜索。"""

[time_query_tool_description]
other = "调用此工具获取当前的本地日期、时间和时区信息。当用户询问当前日期、时间、时区，或其它时间敏感的问题时使用。"

[web_search_tool_description]
other = "当需要实时信息（如天气、新闻、股票价格、汇率、最新事件等）时，调用此工具进行网络搜索。根据用户的输入生成搜索关键词列表。"

[web_search_param_description]
other = "搜索关键词。对于必须完整匹配的精确短语，使用双引号括起来，例如：\"Hello world\"。多个概念之间用空格组合。示例：C++ \"Hello world\" 历史"

[tool_execution_failed]
other = "工具执行失败：{{.Error}}"

[set_tool_argument_faild]
other = "设置工具参数失败：{{.Error}}"

[web_search_tool_searching]
other = "正在搜索"

[time_query_tool_pending]
other = "让我看一下当前时间……"

[server_error]
other = "哎呀！服务端出错啦！\n{{.Error}}"

[session_title_system_prompt]
other = "你是一个标题生成助手。下面我会提供一段对话内容，其中 A 代表用户（提问方），B 代表 AI 助手（回答方）。请根据对话内容，生成一个简洁、准确的标题，长度严格控制在15个汉字以内。直接输出标题即可，不要多余的解释。"
