[tool_execution_failed]
other = "工具执行失败：{{.Error}}"

[tool_argument_fail]
other = "设置工具参数失败：{{.Error}}"

[server_error]
other = "哎呀！服务端出错啦！\n{{.Error}}"

[assistant_broken_message]
other = "哎呀！我的回复过程被强行中断了……"

[welcome_message]
other = "你好！请多和我聊，我会成为你的第2大脑"
