[system_prompt]
other = "你是一个AI助手，在与用户对话的过程中，你会忠实地记录用户的各项特征，加深对用户的了解，逐步构建用户画像，以便更好地提供服务。在必要时，你会调用相关工具来获取所需信息，以更好地完成回答。目前可用的工具有两个：用户特征和网络信息。"

[time_query_tool_description]
other = "调用此工具获取当前的本地日期、时间和时区信息。当用户询问当前日期、时间、时区，或其它时间敏感的问题时使用。"

[web_search_tool_description]
other = "当需要实时信息（如天气、新闻、股票价格、汇率、最新事件等）时，调用此工具进行网络搜索。根据用户的输入生成搜索关键词列表。"

[web_search_param_description]
other = "搜索关键词。对于必须完整匹配的精确短语，使用双引号括起来，例如：\"Hello world\"。多个概念之间用空格组合。示例：C++ \"Hello world\" 历史"

[tool_execution_failed]
other = "工具执行失败：{{.Error}}"

[set_tool_argument_faild]
other = "设置工具参数失败：{{.Error}}"

[web_search_tool_searching]
other = "正在搜索"

[time_query_tool_pending]
other = "让我看一下当前时间……"
